### PR TITLE
Fix/broken images

### PR DESCRIPTION
**Pull request by frederic-klein**
Fix missing images for multiple podcasts by sswitching to rss data import.

### CODE REVIEW

**Comment by iRaul** [comment]
Hey @frederic-klein 👋

Thanks for helping me with this, I've added you as a contributor to this repo.

Can you switch to rss all the images? 🙂

**Comment by frederic-klein** [comment]
Awesome, thanks for the invite. Sure, will update the PR later today.

**Comment by iRaul** [comment]
@frederic-klein 

Can you write me an email to rauldronk@gmail.com please?

**Comment by frederic-klein** [comment]
@iRaul the lazy loading of the RSS data is pretty slow. Working on a google cloud function that will periodically and triggered by a merge into master branch update the rss data and provide all the data in a single REST call. This will give us a much faster time to reactive and a more or less zero maintenance update pipeline. Can you have a look at the truncated titles (hover for full title)?

**Pull request merged**
